// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoungFit.DAL.Context;

#nullable disable

namespace YoungFit.DAL.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20231208162425_Yedi")]
    partial class Yedi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YoungFit.DAL.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Adminler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hasansalgin@gmail.com",
                            Sifre = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ethem@gmail.com",
                            Sifre = "bey110323."
                        },
                        new
                        {
                            Id = 3,
                            Email = "ozdenur@gmail.com",
                            Sifre = "admin1234"
                        });
                });

            modelBuilder.Entity("YoungFit.DAL.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YoungFit.DAL.Entities.KullaniciYemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OgunZamanı")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamKalori")
                        .HasColumnType("int");

                    b.Property<int>("YemekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("YemekId");

                    b.ToTable("KullaniciYemekler");
                });

            modelBuilder.Entity("YoungFit.DAL.Entities.Yemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<string>("OlcuBirimi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte[]>("Resim")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToplamKalori")
                        .HasColumnType("int");

                    b.Property<string>("YemekAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YemekZamani")
                        .HasColumnType("NVARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Yemekler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kalori = 200,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Somon"
                        },
                        new
                        {
                            Id = 2,
                            Kalori = 150,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Ahtapot"
                        },
                        new
                        {
                            Id = 3,
                            Kalori = 180,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Alabalık"
                        },
                        new
                        {
                            Id = 4,
                            Kalori = 160,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Barbun"
                        },
                        new
                        {
                            Id = 5,
                            Kalori = 170,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Çipura"
                        },
                        new
                        {
                            Id = 6,
                            Kalori = 140,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Dil Balığı"
                        },
                        new
                        {
                            Id = 7,
                            Kalori = 120,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Izgara Hamsi"
                        },
                        new
                        {
                            Id = 8,
                            Kalori = 130,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Kızartma Hamsi"
                        },
                        new
                        {
                            Id = 9,
                            Kalori = 250,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Havyar"
                        },
                        new
                        {
                            Id = 10,
                            Kalori = 220,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Istakoz"
                        },
                        new
                        {
                            Id = 11,
                            Kalori = 180,
                            OlcuBirimi = "Gram",
                            YemekAdi = "İstavrit"
                        },
                        new
                        {
                            Id = 12,
                            Kalori = 200,
                            OlcuBirimi = "Adet",
                            YemekAdi = "İstiridye"
                        },
                        new
                        {
                            Id = 13,
                            Kalori = 150,
                            OlcuBirimi = "Gram",
                            YemekAdi = "İzmarit"
                        },
                        new
                        {
                            Id = 14,
                            Kalori = 190,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Kalkan Balığı"
                        },
                        new
                        {
                            Id = 15,
                            Kalori = 160,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Karides Güveç"
                        },
                        new
                        {
                            Id = 16,
                            Kalori = 170,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Tereyağda Karides"
                        },
                        new
                        {
                            Id = 17,
                            Kalori = 160,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Kefal Balığı"
                        },
                        new
                        {
                            Id = 18,
                            Kalori = 180,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Kılıç Balığı"
                        },
                        new
                        {
                            Id = 19,
                            Kalori = 150,
                            OlcuBirimi = "Gram",
                            YemekAdi = "İzmarit"
                        },
                        new
                        {
                            Id = 20,
                            Kalori = 170,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Lüfer"
                        },
                        new
                        {
                            Id = 21,
                            Kalori = 160,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Mezgit"
                        },
                        new
                        {
                            Id = 22,
                            Kalori = 130,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Midye Dolma"
                        },
                        new
                        {
                            Id = 23,
                            Kalori = 140,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Midye Tava"
                        },
                        new
                        {
                            Id = 24,
                            Kalori = 180,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Palamut"
                        },
                        new
                        {
                            Id = 25,
                            Kalori = 160,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Sardalya"
                        },
                        new
                        {
                            Id = 26,
                            Kalori = 170,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Sazan"
                        },
                        new
                        {
                            Id = 27,
                            Kalori = 210,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Deniz Tarağı"
                        },
                        new
                        {
                            Id = 28,
                            Kalori = 140,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Tekir"
                        },
                        new
                        {
                            Id = 29,
                            Kalori = 200,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Ton Balığı"
                        },
                        new
                        {
                            Id = 30,
                            Kalori = 250,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Sushi"
                        },
                        new
                        {
                            Id = 31,
                            Kalori = 150,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Haşlanmış Tavuk Göğsü"
                        },
                        new
                        {
                            Id = 32,
                            Kalori = 200,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Pişmiş Tavuk Eti"
                        },
                        new
                        {
                            Id = 33,
                            Kalori = 180,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Kızarmış Tavuk Kanadı"
                        },
                        new
                        {
                            Id = 34,
                            Kalori = 220,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Kızarmış Tavuk But"
                        },
                        new
                        {
                            Id = 35,
                            Kalori = 200,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Haşlanmış Tavuk But"
                        },
                        new
                        {
                            Id = 36,
                            Kalori = 150,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Tavuk Köftesi"
                        },
                        new
                        {
                            Id = 37,
                            Kalori = 190,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Tavuk Ciğeri"
                        },
                        new
                        {
                            Id = 38,
                            Kalori = 50,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Ahududu"
                        },
                        new
                        {
                            Id = 39,
                            Kalori = 40,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Böğürtlen"
                        },
                        new
                        {
                            Id = 40,
                            Kalori = 30,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Yeşil Erik"
                        },
                        new
                        {
                            Id = 41,
                            Kalori = 25,
                            OlcuBirimi = "Adet",
                            YemekAdi = "İncir"
                        },
                        new
                        {
                            Id = 42,
                            Kalori = 20,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Dut"
                        },
                        new
                        {
                            Id = 43,
                            Kalori = 35,
                            OlcuBirimi = "Gram",
                            YemekAdi = "Üzüm"
                        },
                        new
                        {
                            Id = 44,
                            Kalori = 40,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Nar"
                        },
                        new
                        {
                            Id = 45,
                            Kalori = 30,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Şeftali"
                        },
                        new
                        {
                            Id = 46,
                            Kalori = 15,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Limon"
                        },
                        new
                        {
                            Id = 47,
                            Kalori = 30,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Kırmızı Erik"
                        },
                        new
                        {
                            Id = 48,
                            Kalori = 200,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Sütlaç"
                        },
                        new
                        {
                            Id = 49,
                            Kalori = 220,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Kazandibi"
                        },
                        new
                        {
                            Id = 50,
                            Kalori = 180,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Magnolia"
                        },
                        new
                        {
                            Id = 51,
                            Kalori = 250,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Tiramisu"
                        },
                        new
                        {
                            Id = 52,
                            Kalori = 280,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Cheesecake"
                        },
                        new
                        {
                            Id = 53,
                            Kalori = 190,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Güllaç"
                        },
                        new
                        {
                            Id = 54,
                            Kalori = 180,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Tavuk Göğsü Tatlısı"
                        },
                        new
                        {
                            Id = 55,
                            Kalori = 200,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Muhallebi"
                        },
                        new
                        {
                            Id = 56,
                            Kalori = 160,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Puding"
                        },
                        new
                        {
                            Id = 57,
                            Kalori = 220,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Supangle"
                        },
                        new
                        {
                            Id = 58,
                            Kalori = 240,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Trileçe"
                        },
                        new
                        {
                            Id = 59,
                            Kalori = 180,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Höşmerim"
                        },
                        new
                        {
                            Id = 60,
                            Kalori = 210,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Keşkül"
                        },
                        new
                        {
                            Id = 61,
                            Kalori = 250,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Aşure"
                        },
                        new
                        {
                            Id = 62,
                            Kalori = 200,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Profiterol"
                        },
                        new
                        {
                            Id = 63,
                            Kalori = 170,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Meyveli Dondurma"
                        },
                        new
                        {
                            Id = 64,
                            Kalori = 160,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Sütlü Dondurma"
                        },
                        new
                        {
                            Id = 65,
                            Kalori = 180,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Çikolatalı Dondurma"
                        },
                        new
                        {
                            Id = 66,
                            Kalori = 190,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Sütlü İrmik Tatlısı"
                        },
                        new
                        {
                            Id = 67,
                            Kalori = 250,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "İrmik Helvası"
                        },
                        new
                        {
                            Id = 68,
                            Kalori = 280,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Un Helvası"
                        },
                        new
                        {
                            Id = 69,
                            Kalori = 320,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Baklava"
                        },
                        new
                        {
                            Id = 70,
                            Kalori = 280,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Kadayıf"
                        },
                        new
                        {
                            Id = 71,
                            Kalori = 300,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Soğuk Baklava"
                        },
                        new
                        {
                            Id = 72,
                            Kalori = 270,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Tulumba"
                        },
                        new
                        {
                            Id = 73,
                            Kalori = 240,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Kemalpaşa"
                        },
                        new
                        {
                            Id = 74,
                            Kalori = 280,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Halka Tatlısı"
                        },
                        new
                        {
                            Id = 75,
                            Kalori = 290,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Şam Tatlısı"
                        },
                        new
                        {
                            Id = 76,
                            Kalori = 300,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Şöbiyet"
                        },
                        new
                        {
                            Id = 77,
                            Kalori = 310,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Künefe"
                        },
                        new
                        {
                            Id = 78,
                            Kalori = 260,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Şekerpare"
                        },
                        new
                        {
                            Id = 79,
                            Kalori = 270,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Revani"
                        },
                        new
                        {
                            Id = 80,
                            Kalori = 280,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Lokma Tatlısı"
                        },
                        new
                        {
                            Id = 81,
                            Kalori = 290,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kalburabastı"
                        },
                        new
                        {
                            Id = 82,
                            Kalori = 310,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Fıstıklı Sarma Tatlısı"
                        },
                        new
                        {
                            Id = 83,
                            Kalori = 260,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Un Helvası"
                        },
                        new
                        {
                            Id = 84,
                            Kalori = 280,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "San Sebastian"
                        },
                        new
                        {
                            Id = 85,
                            Kalori = 150,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Tam Yağlı İnek Sütü"
                        },
                        new
                        {
                            Id = 86,
                            Kalori = 120,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Yarım Yağlı İnek Sütü"
                        },
                        new
                        {
                            Id = 87,
                            Kalori = 140,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Keçi Sütü"
                        },
                        new
                        {
                            Id = 88,
                            Kalori = 100,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Soya Sütü"
                        },
                        new
                        {
                            Id = 89,
                            Kalori = 130,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Badem Sütü"
                        },
                        new
                        {
                            Id = 90,
                            Kalori = 100,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Beyaz Peynir"
                        },
                        new
                        {
                            Id = 91,
                            Kalori = 110,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Süzme Peynir"
                        },
                        new
                        {
                            Id = 92,
                            Kalori = 120,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Lor Peyniri"
                        },
                        new
                        {
                            Id = 93,
                            Kalori = 130,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kaşar Peyniri"
                        },
                        new
                        {
                            Id = 94,
                            Kalori = 140,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Labne"
                        },
                        new
                        {
                            Id = 95,
                            Kalori = 150,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Örgü Peynir"
                        },
                        new
                        {
                            Id = 96,
                            Kalori = 160,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Dil Peyniri"
                        },
                        new
                        {
                            Id = 97,
                            Kalori = 170,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Hellim Peyniri"
                        },
                        new
                        {
                            Id = 98,
                            Kalori = 120,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Kefir"
                        },
                        new
                        {
                            Id = 99,
                            Kalori = 130,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Yoğurt"
                        },
                        new
                        {
                            Id = 100,
                            Kalori = 100,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Ayran"
                        },
                        new
                        {
                            Id = 101,
                            Kalori = 110,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Cacık"
                        },
                        new
                        {
                            Id = 102,
                            Kalori = 70,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Haşlanmış Yumurta"
                        },
                        new
                        {
                            Id = 103,
                            Kalori = 120,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Omlet"
                        },
                        new
                        {
                            Id = 104,
                            Kalori = 130,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Peynirli Omlet"
                        },
                        new
                        {
                            Id = 105,
                            Kalori = 140,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Mantarlı Omlet"
                        },
                        new
                        {
                            Id = 106,
                            Kalori = 150,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Menemen"
                        },
                        new
                        {
                            Id = 107,
                            Kalori = 160,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Sucuklu Yumurta"
                        },
                        new
                        {
                            Id = 108,
                            Kalori = 170,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kuymak - Mıhlama"
                        },
                        new
                        {
                            Id = 109,
                            Kalori = 180,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Sucuk"
                        },
                        new
                        {
                            Id = 110,
                            Kalori = 190,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Sosis"
                        },
                        new
                        {
                            Id = 111,
                            Kalori = 200,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Dana Salam"
                        },
                        new
                        {
                            Id = 112,
                            Kalori = 210,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Hindi Salam"
                        },
                        new
                        {
                            Id = 113,
                            Kalori = 220,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Dana Jambon"
                        },
                        new
                        {
                            Id = 114,
                            Kalori = 230,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Hindi Jambon"
                        },
                        new
                        {
                            Id = 115,
                            Kalori = 240,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Piliç Jambon"
                        },
                        new
                        {
                            Id = 116,
                            Kalori = 250,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Hindi Füme"
                        },
                        new
                        {
                            Id = 117,
                            Kalori = 260,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Piliç Füme"
                        },
                        new
                        {
                            Id = 118,
                            Kalori = 270,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Pastırma"
                        },
                        new
                        {
                            Id = 119,
                            Kalori = 50,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Siyah Zeytin"
                        },
                        new
                        {
                            Id = 120,
                            Kalori = 60,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Yeşil Zeytin"
                        },
                        new
                        {
                            Id = 121,
                            Kalori = 50,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Bal"
                        },
                        new
                        {
                            Id = 122,
                            Kalori = 60,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Kaymak"
                        },
                        new
                        {
                            Id = 123,
                            Kalori = 70,
                            OlcuBirimi = "SuBardagi",
                            YemekAdi = "Keçi Sütü"
                        },
                        new
                        {
                            Id = 124,
                            Kalori = 80,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Cevizli Yaz Helvası"
                        },
                        new
                        {
                            Id = 125,
                            Kalori = 90,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Tahin"
                        },
                        new
                        {
                            Id = 126,
                            Kalori = 100,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Pekmez"
                        },
                        new
                        {
                            Id = 127,
                            Kalori = 110,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Tahin Pekmez"
                        },
                        new
                        {
                            Id = 128,
                            Kalori = 120,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Nutella"
                        },
                        new
                        {
                            Id = 129,
                            Kalori = 130,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Kakaolu Fındık Kreması"
                        },
                        new
                        {
                            Id = 130,
                            Kalori = 140,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Fındık Ezmesi"
                        },
                        new
                        {
                            Id = 131,
                            Kalori = 150,
                            OlcuBirimi = "TatliKasigi",
                            YemekAdi = "Fıstık Ezmesi"
                        },
                        new
                        {
                            Id = 132,
                            Kalori = 220,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Haşlanmış Makarna"
                        },
                        new
                        {
                            Id = 133,
                            Kalori = 230,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Domatesli Makarna"
                        },
                        new
                        {
                            Id = 134,
                            Kalori = 240,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Spagetti Bolonez"
                        },
                        new
                        {
                            Id = 135,
                            Kalori = 250,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Penne Arabiata"
                        },
                        new
                        {
                            Id = 136,
                            Kalori = 260,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Fettucini Alfredo"
                        },
                        new
                        {
                            Id = 137,
                            Kalori = 270,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Lazanya"
                        },
                        new
                        {
                            Id = 138,
                            Kalori = 280,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Fırında Makarna"
                        },
                        new
                        {
                            Id = 139,
                            Kalori = 290,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Makarna Salatası"
                        },
                        new
                        {
                            Id = 140,
                            Kalori = 10,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Ketçap"
                        },
                        new
                        {
                            Id = 141,
                            Kalori = 20,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Mayonez"
                        },
                        new
                        {
                            Id = 142,
                            Kalori = 15,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Hardal"
                        },
                        new
                        {
                            Id = 143,
                            Kalori = 25,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Barbekü Sos"
                        },
                        new
                        {
                            Id = 144,
                            Kalori = 30,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Ranch Sos"
                        },
                        new
                        {
                            Id = 145,
                            Kalori = 35,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Buffalo Sos"
                        },
                        new
                        {
                            Id = 146,
                            Kalori = 40,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Pesto Sos"
                        },
                        new
                        {
                            Id = 147,
                            Kalori = 15,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Nar Ekşisi"
                        },
                        new
                        {
                            Id = 148,
                            Kalori = 25,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Köri Sos"
                        },
                        new
                        {
                            Id = 149,
                            Kalori = 20,
                            OlcuBirimi = "YemekKasigi",
                            YemekAdi = "Soya Sos"
                        },
                        new
                        {
                            Id = 150,
                            Kalori = 200,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Çıtır Tavuk"
                        },
                        new
                        {
                            Id = 151,
                            Kalori = 300,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Tavuk Burger"
                        },
                        new
                        {
                            Id = 152,
                            Kalori = 350,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Cheeseburger"
                        },
                        new
                        {
                            Id = 153,
                            Kalori = 280,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Etli Ekmek"
                        },
                        new
                        {
                            Id = 154,
                            Kalori = 200,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Lahmacun"
                        },
                        new
                        {
                            Id = 155,
                            Kalori = 300,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Et Döner Dürüm"
                        },
                        new
                        {
                            Id = 156,
                            Kalori = 350,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kumpir"
                        },
                        new
                        {
                            Id = 157,
                            Kalori = 400,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Adana Dürüm"
                        },
                        new
                        {
                            Id = 158,
                            Kalori = 450,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Urfa Dürüm"
                        },
                        new
                        {
                            Id = 159,
                            Kalori = 250,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Patates Kızartması"
                        },
                        new
                        {
                            Id = 160,
                            Kalori = 300,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Soğan Halkası"
                        },
                        new
                        {
                            Id = 161,
                            Kalori = 350,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kıymalı Pide"
                        },
                        new
                        {
                            Id = 162,
                            Kalori = 400,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kaşarlı Pide"
                        },
                        new
                        {
                            Id = 163,
                            Kalori = 450,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kuşbaşılı Pide"
                        },
                        new
                        {
                            Id = 164,
                            Kalori = 200,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Dana Eti"
                        },
                        new
                        {
                            Id = 165,
                            Kalori = 250,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kuzu Eti"
                        },
                        new
                        {
                            Id = 166,
                            Kalori = 300,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Etli Sebzeli Pizza"
                        },
                        new
                        {
                            Id = 167,
                            Kalori = 280,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kızarmış Hindi Eti"
                        },
                        new
                        {
                            Id = 168,
                            Kalori = 320,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kaz Eti"
                        },
                        new
                        {
                            Id = 169,
                            Kalori = 290,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Keçi Eti"
                        },
                        new
                        {
                            Id = 170,
                            Kalori = 350,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Kurutulmuş Sığır Eti"
                        },
                        new
                        {
                            Id = 171,
                            Kalori = 230,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Etli Nohut"
                        },
                        new
                        {
                            Id = 172,
                            Kalori = 300,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Et Döner"
                        },
                        new
                        {
                            Id = 173,
                            Kalori = 350,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Et Kavurma"
                        },
                        new
                        {
                            Id = 174,
                            Kalori = 320,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Et Sote"
                        },
                        new
                        {
                            Id = 175,
                            Kalori = 400,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Dana Etli Burrito"
                        },
                        new
                        {
                            Id = 176,
                            Kalori = 280,
                            OlcuBirimi = "Porsiyon",
                            YemekAdi = "Etli Kuru Fasulye"
                        },
                        new
                        {
                            Id = 177,
                            Kalori = 20,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Domates"
                        },
                        new
                        {
                            Id = 178,
                            Kalori = 15,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Çeri Domates"
                        },
                        new
                        {
                            Id = 179,
                            Kalori = 25,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Salatalık"
                        },
                        new
                        {
                            Id = 180,
                            Kalori = 10,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Marul"
                        },
                        new
                        {
                            Id = 181,
                            Kalori = 15,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Çarliston Biber"
                        },
                        new
                        {
                            Id = 182,
                            Kalori = 20,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Kırmızı Biber"
                        },
                        new
                        {
                            Id = 183,
                            Kalori = 10,
                            OlcuBirimi = "Adet",
                            YemekAdi = "Turp"
                        },
                        new
                        {
                            Id = 184,
                            Kalori = 180,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Ezogelin Çorbası"
                        },
                        new
                        {
                            Id = 185,
                            Kalori = 250,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "İşkembe Çorbası"
                        },
                        new
                        {
                            Id = 186,
                            Kalori = 200,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Kırmızı Mercimek Çorbası"
                        },
                        new
                        {
                            Id = 187,
                            Kalori = 190,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Yeşil Mercimek Çorbası"
                        },
                        new
                        {
                            Id = 188,
                            Kalori = 150,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Sebze Çorbası"
                        },
                        new
                        {
                            Id = 189,
                            Kalori = 180,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Tarhana Çorbası"
                        },
                        new
                        {
                            Id = 190,
                            Kalori = 160,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Yayla Çorbası"
                        },
                        new
                        {
                            Id = 191,
                            Kalori = 140,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Tavuk Çorbası"
                        },
                        new
                        {
                            Id = 192,
                            Kalori = 120,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Balkabağı Çorbası"
                        },
                        new
                        {
                            Id = 193,
                            Kalori = 170,
                            OlcuBirimi = "Tabak",
                            YemekAdi = "Mantar Çorbası"
                        });
                });

            modelBuilder.Entity("YoungFit.DAL.Entities.KullaniciYemek", b =>
                {
                    b.HasOne("YoungFit.DAL.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciYemekler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungFit.DAL.Entities.Yemek", "Yemek")
                        .WithMany("KullaniciYemekler")
                        .HasForeignKey("YemekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Yemek");
                });

            modelBuilder.Entity("YoungFit.DAL.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciYemekler");
                });

            modelBuilder.Entity("YoungFit.DAL.Entities.Yemek", b =>
                {
                    b.Navigation("KullaniciYemekler");
                });
#pragma warning restore 612, 618
        }
    }
}
